#!/bin/sh

export PKG_CONFIG_PATH="$(opam config var prefix)/lib/pkgconfig"

# Bridge through $XEN_CFLAGS from the environment into Oasis' world.
#
XEN_CFLAGS="disabled"
grep -q '^xen="true"' setup.data && XEN_CFLAGS="$(pkg-config --static mirage-xen --cflags)"
echo "XEN_CFLAGS=\"${XEN_CFLAGS}\"" >> setup.data

FREESTANDING_CFLAGS="disabled"
grep -q '^solo5="true"' setup.data && FREESTANDING_CFLAGS="$(pkg-config ocaml-freestanding --cflags)"
echo "FREESTANDING_CFLAGS=\"${FREESTANDING_CFLAGS}\"" >> setup.data

# Kill CPU acceleration if requested in ./configure, but:
# * unsupported by the current host CPU;
# * unsupported by the current toolchain; or
# * disabled via NOCRYPTO_NO_ACCEL env var.
#
test_platform () {
  CPUDETECT=$(mktemp -t nocrypto.XXXXXX)
  (cc src/native/cpudetect_static.c -o ${CPUDETECT} > /dev/null 2>&1 && ${CPUDETECT})
  ok=$?
  rm -f ${CPUDETECT}
  return $ok
}
if grep -q '^modernity="true"' setup.data; then
  [ -z $NOCRYPTO_NO_ACCEL ] && test_platform || echo "modernity=\"false\"" >> setup.data
fi
